# Railway.app configuration
# https://railway.app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python run.py production"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
